# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow
import sys


def start():
    import WaitingWindow
    print(1)
    # app = QApplication(sys.argv)
    # from RunApp import mainWindow
    mainWindow = QMainWindow()
    ui = WaitingWindow.Ui_MainWindow()
    ui.setupUi(mainWindow)
    # 显示窗口
    mainWindow.show()
    # sys.exit(app.exec_())


class Ui_MainWindow(object):
    def setupUi(self, mainWindow):
        self.mainWindow = mainWindow
        mainWindow.setObjectName("MainWindow")
        mainWindow.resize(800, 600)
        mainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(30, 150, 751, 81))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title.setFont(font)
        self.title.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title.setTextFormat(QtCore.Qt.AutoText)
        self.title.setScaledContents(False)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setIndent(-1)
        self.title.setObjectName("title")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(70, 350, 281, 71))
        font = QtGui.QFont()
        font.setFamily("3ds Light")
        font.setPointSize(16)
        self.startButton.setFont(font)
        self.startButton.setIconSize(QtCore.QSize(30, 50))
        self.startButton.setAutoDefault(True)
        self.startButton.setDefault(False)
        self.startButton.setObjectName("startButton")
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setGeometry(QtCore.QRect(450, 350, 281, 71))
        font = QtGui.QFont()
        font.setFamily("3ds Light")
        font.setPointSize(16)
        self.closeButton.setFont(font)
        self.closeButton.setIconSize(QtCore.QSize(30, 50))
        self.closeButton.setAutoDefault(True)
        self.closeButton.setDefault(False)
        self.closeButton.setObjectName("closeButton")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        self.startButton.clicked.connect(start)
        self.startButton.clicked.connect(QMainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Welcome to SWS3009 Group7 Advanced Model "))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.closeButton.setText(_translate("MainWindow", "Close"))
