# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WaitingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(90, 170, 631, 81))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title.setFont(font)
        self.title.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title.setTextFormat(QtCore.Qt.AutoText)
        self.title.setScaledContents(False)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setIndent(-1)
        self.title.setObjectName("title")
        self.title_2 = QtWidgets.QLabel(self.centralwidget)
        self.title_2.setGeometry(QtCore.QRect(90, 310, 631, 81))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_2.setFont(font)
        self.title_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.title_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_2.setTextFormat(QtCore.Qt.AutoText)
        self.title_2.setScaledContents(False)
        self.title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.title_2.setIndent(-1)
        self.title_2.setObjectName("title_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Waiting for Video and Audio Recording..."))
        self.title_2.setText(_translate("MainWindow", "Recognition Starts..."))
